plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

permalink: /blog/:year/:month/:title/
future: true

collections:
  tracks:
    output: true
    permalink: /kart-setup/:path/
  brands:
    output: true
    permalink: /kart-brand/:path/
  classes:
    output: true
    permalink: /kart-class/:path/

paginate: 10
paginate_path: "/blog/page:num"

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      author: "Jon Alter"

# General
name: KartBalance
tagline: Balance your kart
baseurl: ""
url: "https://kartbalance.com" # the base hostname & protocol for your site

# SEO
# kart,karting,balance,weight,distribution,scaling,calculator,center,gravity,ratio,scale,chassis,race
title: KartBalance
description: Professional kart weight distribution calculator app for iOS. Calculate corner weights, chassis balance, and center of gravity for optimal racing kart setup. Free download.

# favicon
favicon: /favicon.png

# Jekyll
exclude: ['Rakefile', 'Gemfile', 'Gemfile.lock', 'vendor', 'vendor/**/*', 'vendor/bundle', 'vendor/bundle/**/*', 'scripts']
markdown: kramdown

# App Store
appstore_url: https://apps.apple.com/us/app/kartbalance/id1151974965
appstore: <a href="https://apps.apple.com/us/app/kartbalance/id1151974965" class="app-store" rel="external nofollow"><img src="/assets/app-store-black.svg" alt="Download on the App Store"></a>
appstore_white: <a href="https://apps.apple.com/us/app/kartbalance/id1151974965" class="app-store" rel="external nofollow"><img src="/assets/app-store-white.svg" alt="Download on the App Store"></a>

# Screenshots
screenshots:
- screenshot01
- screenshot02

# Company Info
company: Jon Alter
company_website: http://kartbalance.com

# Emails
email_contact: kartbalanceapp@gmail.com
email_support: kartbalanceapp@gmail.com
