# General
name: KartBalance
tagline: Balance your kart
baseurl: ""
url: "http://jonalter.github.io" # the base hostname & protocol for your site
# favicon
favicon: /favicon.png

# Jekyll
exclude: ['Rakefile']
markdown: kramdown

# App Store
appstore_url: http://itunes.com/apps/kartbalance
appstore: <a href="http://itunes.com/apps/kartbalance" class="app-store" rel="external nofollow"><img src="/assets/app-store-black.svg" alt="Download on the App Store"></a>
appstore_white: <a href="http://itunes.com/apps/kartbalance" class="app-store" rel="external nofollow"><img src="/assets/app-store-white.svg" alt="Download on the App Store"></a>

# Screenshots
screenshots:
- screenshot01
- screenshot02

# Company Info
company: jalter
company_website: http://kartbalance.com

# Emails
email_press: kartbalanceapp@gmail.com
email_contact: kartbalanceapp@gmail.com
email_support: kartbalanceapp@gmail.com
