plugins:
  - jekyll-seo-tag

# General
name: KartBalance
tagline: Balance your kart
baseurl: ""
url: "http://jonalter.github.io" # the base hostname & protocol for your site

# SEO
# kart,karting,balance,weight,distribution,scaling,calculator,center,gravity,ratio,scale,chassis,race
title: Kart Balance and Weight Distribution Calculator App
description: An easy to use chassis balance and weight distribution calculator for scaling and adding weights to a kart

# favicon
favicon: /favicon.png

# Jekyll
exclude: ['Rakefile']
markdown: kramdown

# App Store
appstore_url: http://itunes.com/apps/kartbalance
appstore: <a href="https://itunes.apple.com/us/app/kartbalance/id1151974965?ls=1&mt=8" class="app-store" rel="external nofollow"><img src="/assets/app-store-black.svg" alt="Download on the App Store"></a>
appstore_white: <a href="https://itunes.apple.com/us/app/kartbalance/id1151974965?ls=1&mt=8" class="app-store" rel="external nofollow"><img src="/assets/app-store-white.svg" alt="Download on the App Store"></a>

# Google services
google_analytics: UA-83573292-3

# Screenshots
screenshots:
- screenshot01
- screenshot02

# Company Info
company: Jon Alter
company_website: http://kartbalance.com

# Emails
email_press: kartbalanceapp@gmail.com
email_contact: kartbalanceapp@gmail.com
email_support: kartbalanceapp@gmail.com
