version: "3.9"

services:
  jekyll:
    image: ruby:3.3
    command: bash /srv/jekyll/docker-start.sh
    working_dir: /srv/jekyll
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - .:/srv/jekyll
    environment:
      - JEKYLL_ENV=development
