source "https://rubygems.org"

gem "jekyll", "~> 3.9"
gem "jekyll-seo-tag", "~> 2.8"
gem "jekyll-feed", "~> 0.15"
gem "jekyll-paginate", "~> 1.1"
gem "kramdown-parser-gfm", "~> 1.1"
gem "sass", "~> 3.7"
gem "webrick", "~> 1.8"
gem "rake", "~> 13.0"
